# use the latest ubuntu environment (18.04) available on travis
dist: xenial

language: go

# Force-enable Go modules.
env:
  - GO111MODULE=on

go:
  - 1.12.x

# Don't email me the results of the test runs.
notifications:
  email: false

# go test
script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled